### ISSUE TITLE
TDC - Importer les donneés du coastline service 

### ISSUE THREAD

**Issue by pierrejego** [jdev-org/madDog#10]
## Description

Le retour du coastline service bien qu'indiqué en csv n'en n'est pas un.

**En tant qu**'utilisateur
**Je souhaite** pour voir dans un graphique les données de comparaison de traits de côte
**Afin de** me permettre d'analyser facilement la situation

## (Si) Règles spécifiques - Règles métiers

Le service WPS actuellement déployé ne fonctionne qu'avec au minimun 2 traits de côtes.
L'utilisateur doit pouvoir choisir parmi les traits de côte existants puis lancer le traitement
Une radial et un graphique avec les informations du fichier du retour du WPS doit alors apparaître à l'écran

Il faut valider avec @mrouan  lors de la réunion d'ergonomie le rendu du tableau en fonction des données a afficher

## (Si) Tests d'acceptabilité

Sur l'application, l'utilisateur choisi un site puis au moins deux traits de côtes, il clique sur post-traitement. 
La radial et un graphique doit alors apparaître.

## Complément (graphique, capture, schéma, etc.)

Exemple de données de retour du WPS à tranformer en tableau
1952-06-10|2021-07-05
rad|separe;cumule;taux
R3|0.030725405474946395;0.030725405474946395;1.218005449732276E-6
R4|4.268340219944022;4.268340219944022;1.6920400459621114E-4
R5|4.2953599094313235;4.2953599094313235;1.7027510938838196E-4
R6|2.726834286486608;2.726834286486608;1.080961819744156E-4
R7|-0.034952399845819944;-0.034952399845819944;-1.3855704370815802E-6
R8|0.04460988807140122;0.04460988807140122;1.7684091045509086E-6
R9|-3.5177404572449187;-3.5177404572449187;-1.394489993358011E-4
R10|-3.2293986038424483;-3.2293986038424483;-1.2801865550790645E-4
R11|-2.876038922063463;-2.876038922063463;-1.1401089836135189E-4

exemple existant
![image](https://user-images.githubusercontent.com/11499415/165907489-1f90656b-e463-48b4-a952-e464c709b052.png)

**Comment by pierrejego** [comment]
Un point est à faire avec l'équipe LETG pour voir comment simplifier le retour des données pour une vision en graphe. Les | présents demandent un traitement complémentaire côté front

**Comment by pierrejego** [comment]
https://github.com/LETG/coastlinetracking/issues/10

**Comment by Gaetanbrl** [comment]
à fermer @pierrejego ?
