### ISSUE TITLE
GENERAL - Zoom sur le site

### ISSUE THREAD

**Issue by pierrejego** [jdev-org/madDog#12]
## Description

**En tant qu'**Utilisateur
**Je souhaite** que la carte zoom sur le site sur lequel j'ai cliqué
**Afin d'**améliorer la compréhension de la sélection

## (Si) Tests d'acceptabilité

- [x] L'utilisateur clique sur un site pour sélectionner un site, la carte zoom alors sur cette partie.
- [x] L'utilisateur clique sur une commune pour zoomer sur l'emprise des sites de cette commune.
- [x] Le site est sélectionner dans la partie droite ou sur la carte directement, permettant ainsi de lancer les traitements.
- [x] L'emprise du site disparaît de la carte lorsqu'il a été cliqué (uniquement si un sites est sélectionné)

## Complément (graphique, capture, schéma, etc.)

Actuellement 
![image](https://user-images.githubusercontent.com/11499415/165908917-5e95682a-d876-49d3-9a83-2d5394cd8074.png)

souhaité
![image](https://user-images.githubusercontent.com/11499415/165908983-a51768a4-940e-4488-bd12-5bc53f6ba792.png)

**Comment by Gaetanbrl** [comment]
> L'utilisateur clique sur un site ou une commune

Zoom à prévoir si on clique sur une commune également ?
