### ISSUE TITLE
IHM - Paramétrage et visualisation des résultats pour le service Profils de plage

### ISSUE THREAD

**Issue by Agath21** [jdev-org/madDog#17]
## Description

**En tant que** Utilisateur
**Je souhaite** sélectionner un profil de plage sur la carte au sein du site d'étude
**Afin de** visualiser l'évolution du bilan sédimentaire dans le temps sur le profil sélectionné

## (Si) Règles spécifiques - Règles métiers

- A minima un profil et une date doivent être sélectionnés

## (Si) Tests d'acceptabilité

- [x] Je peux sélectionner un profil sur la carte et via un système de liste
- [x] Je peux sélectionner différentes dates du profil dans le graphique grâce à un système intuitif 
- [x] Je peux modifier les paramètres initiaux du service WPS 
- [x] Je peux visualiser l'évolution du profil de plage grâce à un graphique 
- [x] Je peux exporter mes résultats en png

**Comment by Agath21** [comment]
# Solution(s) proposée(s)
## Maquettes


_Maquettes non contractuelles, les données visualisées sont inventées pour les besoins de compréhension des fonctionnalités_

## Parcours utilisateurs
Après avoir sélectionné le service "Profil de plage" dans la liste, l'utilisateur doit suivre les étapes suivantes : 

**CARTE**

1 - L'utilisateur doit sélectionner profil sur la carte


**Onglet PARAMÈTRES DU SERVICE**

2 - L'utilisateur sélectionne une ou des dates pour le profil qu'il visualise sur le graphique grâce à la boîte de sélection (groupés par année). Il peut également effectuer une recherche de date.
> Le graphique s'ajuste selon les sélections

3 - L'utilisateur peut modifier les paramètres initiaux du service en dépliant une boîte grâce à l'icône +
- un interval d’interpolation ( un chiffre avec virgule possible)
- un boolean (useSmallestDistance)
- un minDist ( un chiffre avec virgule possible)
- un maxDist ( un chiffre avec virgule possible)

4 - On lance le traitement via le bouton associé. Il est aussi possible de supprimer tous les paramètres via le bouton "Réinitialiser"

> En cliquant sur le bouton de lancement, l'application doit changer d'onglet sans action de l'utilisateur  pour afficher le graphique



**Onglet VISUALISATION DES RÉSULTATS**

5 - L'utilisateur visualise l'évolution du bilan sédimentaire aux dates choisies. 
> En bar = évolution depuis n-1
> En ligne = évolution cumulée

6 - L'utilisateur peut ensuite exporter le graph en png

## Fonctionnalités IHM mobilisées et démo
Système d'onglet pour switcher entre les paramètres et résultats :
- Bootstrap / Navs et Tabs 
- https://getbootstrap.com/docs/5.0/components/navs-tabs/

Système de multi sélection avec barre de recherche 
- Bootstrap et jQuery
- Méthode : https://www.jquery-az.com/10-demos-of-bootstrap-multiselect-dropdown-by-using-jquery/
- Démo avec barre de recherche : https://www.jquery-az.com/boots/demo.php?ex=63.0_9
- Démo avec groupes : https://www.jquery-az.com/boots/demo.php?ex=63.0_5
- Démo supplémentaire : https://admirhodzic.github.io/multiselect-dropdown/demo.html 

Système d'affichage des paramètres avancés en accordéon 
- Bootstrap / Collapse
- https://getbootstrap.com/docs/5.0/components/collapse/

## À définir

- [ ]  Titre et méthode du service
- [ ] Titre du graphique de sélection des profils et axes
- [ ]  Intitulés des paramètres avancés + textes descriptifs lors du survol de l'icône
- [ ]  Intitulés du graphique, des axes (+ unités) et des éléments visualisés (bar et courbe)

**Comment by Agath21** [comment]
ETAPE 1 - Ajout d'une liste pour sélectionner un profil de plage en plus de la sélection sur la carte :

![MADDOG_maquetteInterface_selectPP](https://user-images.githubusercontent.com/22764056/166664800-4a208584-52a7-435c-9ca6-f3f996bf45b5.png)

**Comment by pierrejego** [comment]
Les données sont dans la couche maddog:prf

**Comment by Gaetanbrl** [comment]
> Les données d'élévation sont dans chaque point des lineString

le json de retour WFS renvoi bien X,Y,Z.
Quelles sont les données à utiliser pour la distance (axe X du graphique des profils sélectionnés) ?

**Comment by Gaetanbrl** [comment]
Suite au cotech du 30/05 : 

- [ ] Reset total à la sortie
- [ ] Gérer les invalid dates avec FF

**Comment by pierrejego** [comment]
- [ ] Améliorer l'ergonomie de sélection du profil ( Changement de curseur au survol / tooltip / affichage nom du profil) @Agath21  il faudra proposer une solution à @mrouan sur ce point

**Comment by Agath21** [comment]
Ajout d'une liste de sélection des profils en supplément de la carte :
![image](https://user-images.githubusercontent.com/22764056/172143406-e1d67254-cf4a-4b48-a3be-05801d211f07.png)

**Comment by Agath21** [comment]
- [ ] Intitulés des paramètres avancés + textes descriptifs lors du survol de l'icône

**Comment by Gaetanbrl** [comment]
En l'état nous n'arrivons pas à reproduire le graphique de Serge sur le profile 1 VOUGOT.
Vu avec @mrouan, champs et données à valider avec Serge vu les résultats dans le graphiques du bilan sédimentaire.
