### ISSUE TITLE
IHM - Page d'accueil 

### ISSUE THREAD

**Issue by Agath21** [jdev-org/madDog#20]
## Description

**En tant que** Utilisateur 
**Je souhaite** accéder à la page d'accueil 
**Afin de** avoir des informations sur le contexte du projet, les actualités, l'équipe ...

## (Si) Tests d'acceptabilité

- [x] J'accède à la page d'accueil lors du démarrage de l'app et depuis le bouton `home`
- [x] J'ai des informations concernant le projet, ses actualités, ses partenaires 
- [x] J'ai une adresse mail pour contacter l'équipe en charge de l'application 
- [x] J'ai des informations sur les données utilisées, leurs provenances et les méthodes utilisées.

**Comment by pierrejego** [comment]
En attente du contenu éditorial

**Comment by pierrejego** [comment]
- [ ] Ajout du flux rss de geonetwork

**Comment by mrouan** [comment]
https://portail.indigeo.fr/geonetwork/srv/fre/rss.search?georss=simplepoint&keyword=MADDOG
ou
https://portail.indigeo.fr/geonetwork/srv/fre/rss.search?keyword=MADDOG

**Comment by Agath21** [comment]
Tâches à réaliser : 

- [ ] Intégrer les actualités sous forme de flux RSS (à fournir par l'équipe LETG + mécanique mise en place du côté Jdev) 
- [ ] Intégrer un système de pagination pour les actualités et le catalogue de données 
- [ ] MAJ des rubriques Accueil / Projet et Contact 

Que fait-on avec l'onglet "Publications" ?

**Comment by Agath21** [comment]
- [ ]  Afficher la page d'accueil par défault

**Comment by Agath21** [comment]
- [ ]  onglet partenaire : dans les logos, le logo AGEO ne doit pas apparaître plus grand que le logo Interreg 

- [ ] onglets accueil et à propos : le texte souligné c'était pour vous indiquer là où mettre des liens hypertexte vers les url correspondantes, mais le texte n'a pas besoin d'apparaître en souligné

Les liens sont ceux fournis dans l'onglet ressources, sauf pour 3 qui renvoient vers le site IUEM (en cours de refonte pour la partie observation) liens
- vers l'IUEM :https://www-iuem.univ-brest.fr/
- vers la série des données topo-morphologiques sur l’évolution du littoral : https://www-iuem.univ-brest.fr/observation-iuem/observation-littorale-et-cotiere/serie-dobservations-geomorphologiques/
- vers les séries d’observation littorale et côtière à l’IUEM :https://www-iuem.univ-brest.fr/observation-iuem/observation-littorale-et-cotiere/
