### ISSUE TITLE
GENERAL - FOND DE PLAN

### ISSUE THREAD

**Issue by pierrejego** [jdev-org/madDog#24]
## Description

Décrire ici ce qui est attendu par un personnage clairement identifié.

**En tant qu'**utilisateur
**Je souhaite** pour changer le fond de plan
**Afin de** mieux visualiser les données

## (Si) Règles spécifiques - Règles métiers

- [x] Par défaut affichage sur le positron blanc.
- [x] Affichage des différents fond de plan en mode gallerie
- [x] Ajout d'un texte au survol
- [x] Modifier la liste des fonds de plan (voir commentaire ci-dessous)

## (Si) Tests d'acceptabilité

Une fois arrivée sur la page de l'application, je peux voir et sélectionner un autre fond de plan à partir d'une gallerie située en bas à droite de la carte.

**Comment by mrouan** [comment]
Agathe, merci de bien vouloir mettre les fonds de plan dans l'ordre suivant :
Scan 25 (en haut de la pile)
Photo aérienne 1950
Photo aérienne
Positron (en bas)
