### ISSUE TITLE
TDC / beach profile - Labels numéros de profils sur la carte et les graphiques

### ISSUE THREAD

**Issue by Agath21** [jdev-org/madDog#35]

**Comment by Agath21** [comment]
## Afficher les n° de profils sur la radiale

> Tests réalisées dans la branch feature35

### Solution expérimentée :

Dans le fichiers `tdcUtils.js`, dans la fonction qui définit la radiale `getRadiales`, on ajoute un label à chaque profil comme ceci :
```
var style = new ol.style.Style({
                stroke: new ol.style.Stroke({
                    color: "black",
                    width: 2
                }),
                text: new ol.style.Text({
                    font: '18px Roboto',
                    text: 'profil',
                    placement: 'line',
                    textAlign: 'end',
                    fill: new ol.style.Fill({
                        color: 'black'
                    })
                })
            });
```
![image](https://user-images.githubusercontent.com/22764056/170282363-3208b9b9-d57a-4e90-bab2-98e90f60789b.png)

### Problèmes rencontrées : 
1 . Je n'arrive pas à placer le label à la fin de la radiale. J'ai testé les paramètres suivants sans succès : `textBaseline, offsetX et Y`
2 . Il faut injecter le n° de profil dans la balise text, toutefois je n'ai pas réussi à récupérer le n° pour chaque profil disponible dans la donnée 
![image](https://user-images.githubusercontent.com/22764056/170282603-f2d52a53-dd03-4393-8665-f8b71c16502e.png)

J'ai réussi un début de code mais sans trouver la fin : 

```
let layer = mviewer.getLayer("radiales").layer;
let labelLayer = layer.getSource().idIndex_;
```

**Comment by Agath21** [comment]
## Afficher les n° de profils sur le graphique 

Pour les graphiques des traits de côte, j'ai affiché l'ensemble des n° de profils et rajouter un titre à chaque graphique (à vérifier avec l'équipe)

![image](https://user-images.githubusercontent.com/22764056/170283494-e07a5e7e-a47e-402b-8f30-bedbac7a03c5.png)

Commit associé : https://github.com/jdev-org/madDog/commit/6a4a01af0143b63718707dbafcb57b658a0e88c1

**Comment by Gaetanbrl** [comment]
> 1 . Je n'arrive pas à placer le label à la fin de la radiale. J'ai testé les paramètres suivants sans succès : textBaseline, offsetX et Y
> 2 . Il faut injecter le n° de profil dans la balise text, toutefois je n'ai pas réussi à récupérer le n° pour chaque profil disponible dans

Je regarde.

**Comment by Gaetanbrl** [comment]
> Je n'arrive pas à placer le label à la fin de la radiale. J'ai testé les paramètres suivants sans succès : textBaseline, offsetX et Y

L'alignement sur la ligne ne permet pas de modifier le label sur son axe X mais est uniquement permis sur l'axe Y.
Le paramètre offsetX n'est en l'état pas utilisable.

Il faut utiliser un alignement type point et calculer l'angle selon les coordonnées :
`-Math.atan((last[1] - first[1])/(last[0] - first[0]))`

source: https://gis.stackexchange.com/questions/333475/setting-openlayers-line-labels-by-angle

> Il faut injecter le n° de profil dans la balise text, toutefois je n'ai pas réussi à récupérer le n° pour chaque profil disponible

Est-ce bien le paramètre "name" de la radiale qui est à utiliser ?
Si oui, j'ai déplacé le style pour pouvoir accéder à la feature et ses propriétés : 

`text: `profil ${f.get('name')}`,`

**Comment by Gaetanbrl** [comment]
je laisse @Agath21 valider et fermer cette issue

**Comment by Gaetanbrl** [comment]
Merge OK. Je clos.
