### ISSUE TITLE
GENERAL - Zoom par défaut sur l'ensemble des communes disponibles 

### ISSUE THREAD

**Issue by Agath21** [jdev-org/madDog#37]
## Description

Par défaut, lors de l'ouverture de l'application, je souhaite visualiser l'ensemble des sites et communes disponibles en Bretagne. 

> Régler l'extend de la carte

**Comment by Gaetanbrl** [comment]
Je viens de push sur main une méthode qui permet de zoom sur un WMS en récupérant la BBOX via un getCapabilities.
L'utilisation de la couche de tooltip est faisable mais le code ferait mieux d'être intégré comme méthode principale à partir d'un WMS.

Si on a un WFS on utilise la méthode `tools.zoomToExtent()`.

Les problèmes rencontrés sont toujours les mêmes : 
- les couches / la carte / l'extension ne sont pas accessibles en même temps et à un moment jamais identique, inconnu.
- On zoom sur la couche mais le zoom semble faux car je pense qu'il est calé sur une mauvaise taille de la carte (avant qu'on redimensionne l'écran à 50%).

### Solution

- Dans la couche tooltip, on émet un event qui va dire que la couche est prête, ca veut dire que toutes les couches sont prêtent en général

- Dans maddog.js => Ajouter un listener pour écouter quand la couche tooltip est prête (seule modif dans le WFS).

- Ajouter un setTimeout pour attendre que la carte soit à la bonne taille avant de zoom sur l'étendue des communes

**Comment by Gaetanbrl** [comment]
Testable sur branche `main` @Agath21 @pierrejego

**Comment by Agath21** [comment]
> Testable sur branche `main` @Agath21 @pierrejego

C'est ok pour moi, lors de l'ouverture de l'app, j'ai bien l'ensemble des communes et site zoomées par défaut

**Comment by Gaetanbrl** [comment]
Après l'ajout de communes ce jour par @pierrejego l'extent n'est pas correct.

**Comment by Agath21** [comment]
Le calcul de l'extend est basé sur une requête GetCapabilities sur la couche, toutefois les attributs de la couche ne sont pas mis à jour automatiquement dans Geoserver. Il est nécessaire de les rechargé manuellement. 

Méthode à retranscrire avec une couche WFS afin de le calculer à la volée

**Comment by Agath21** [comment]
> Méthode à retranscrire avec une couche WFS afin de le calculer à la volée

### Solution proposée 
Sur le modèle précédemment crée par @Gaetanbrl , création d'une nouvelle méthode dans `tools.js` pour le zoom sur une couche WFS : 

```
zoomToWMFLayerExtent: (layer, asHome = false) => {
            // generate a GetFeature request
            const featureRequest = new ol.format.WFS().writeGetFeature({
                srsName: 'EPSG:3857',
                featureTypes: [layer],
                outputFormat: 'application/json'
            });
        
            // then post the request and add the received features to a layer
            fetch(mviewer.getLayer(layer).url.replace("wms","wfs"), {
                method: 'POST',
                body: new XMLSerializer().serializeToString(featureRequest),
            }).then(function(response) {
                return response.json();
            }).then(function(json) {
                const layerExtentInit = new ol.source.Vector();
                const features = new ol.format.GeoJSON().readFeatures(json);
                layerExtentInit.addFeatures(features);
                const extent = layerExtentInit.getExtent();
                maddog.bbox = extent;
                // wait 2000 ms correct map size to zoom correctly
                tools.zoomToExtent(maddog.bbox, {duration: 0}, 2000);
                if (asHome) {
                    mviewer.zoomToInitialExtent = () => {
                        tools.zoomToExtent(maddog.bbox);
                    };
                }
            });
        }
```

**Il faut maintenant trouver la solution pour pouvoir le paramétrer dans le `config.json`**

**Comment by Agath21** [comment]
Pour paramétrer la couche du zoom initial, le fichier maddog.js a été modifié à la ligne 11 : 

```
document.addEventListener("communes-ready", () => {
        const defaultZoomOptions = maddog.getCfg("config.options.defaultLayerZoom");
        if (defaultZoomOptions && !_.isEmpty(defaultZoomOptions)) {
            tools.zoomToWFSLayerExtent(defaultZoomOptions.layer, defaultZoomOptions.asHomeExtent);
        }
    });
```
