### ISSUE TITLE
GENERAL - clique sur logo ouvre un nouvel onglet

### ISSUE THREAD

**Issue by mrouan** [jdev-org/madDog#38]
**Description du bug / Describe the bug**

un clique sur le logo ouvre un nouvel onglet

**Reproduire le bug / To Reproduce**

Etapes à suivre pour reproduire votre problème du type : 

1. Aller sur la page https://gis.jdev.fr/mviewer/?config=apps/maddog.xml#
2. Cliquer sur le logo
3. Voir qu'un nouvel onglet s'ouvre

**Comportement attendu / Expected behavior**

Revenir à l'accueil tout en restant dans le même onglet

**Screenshots**

Si possible, une capture d'écran pour nous aider à voir le problème décrit.

**Environnement / Desktop**

Merci de remplir ces informations si connues :
 - OS: [e.g. iOS] : Win10
 - Navigateur / browser [e.g. chrome, safari] Firefox 
 - Version [e.g. 22] 100.0.1

**Informations complémentaires / Additional context**

Préciser par exemple si le problème a été vu suite à l'installation d'une nouvelle version ou suite à des modifications que vous auriez faites ou bien par inadvertance.

**Comment by Gaetanbrl** [comment]
@mrouan par "accueil" il est question de retrouver l'état initial de l'application (avec la modal d'ouverte) ?

**Comment by mrouan** [comment]
oui, pour moi c'est un comportement classique mais j'ai l'impression que tous les mviewer ouvrent un nouvel onglet...

**Comment by Gaetanbrl** [comment]
Je confirme que c'est le comportement natif.

```
<a class="navbar-brand" href="#" target="_blank">
  <img alt="Logo" src="apps/maddog/img/logo_maddog.png" class="mv-logo">
</a>
```

On va ouvrir une issue mviewer sur ce sujet.

**Comment by pierrejego** [comment]
Modification à faire dans le code natif du mviewer, issue et proposition à faire ici
https://github.com/geobretagne/mviewer/issues
