### ISSUE TITLE
TDC - Dessiner une nouvelle ligne de référence

### ISSUE THREAD

**Issue by Agath21** [jdev-org/madDog#41]
## Description

**En tant que** Utilisateur
**Je souhaite** pouvoir dessiner une nouvelle ligne de référence 
**Afin de** visualiser l'évolution du TDC selon la ligne de référence dessinée 

## (Si) Règles spécifiques - Règles métiers

- Cette fonctionnalité est accessible via un bouton depuis les paramètres avancés du suivi TDC
- La nouvelle ligne de référence devra être intégrée au service WPS pour le calcul des graphs

## (Si) Tests d'acceptabilité

- [x] Dans la boîte des paramètres avancés, je peux activer le dessin d'une nouvelle ligne de référence
- [x] Ce même bouton me permet de désactiver la fonction dessin
- [x] Lorsque l'on lance le traitement, les graphiques sont basés sur la ligne de référence dessinée précédemment 
- [x] Quand on clique sur le btn "Réinitialiser", la ligne dessinée est supprimée

## Question(s)

Un nouveau bouton permet-il de réinitialiser le dessin en cas d'erreur de la part de l'utilisateur ?

**Comment by Gaetanbrl** [comment]
> Lorsque l'on lance le traitement, les graphiques sont basés sur la ligne de référence dessinée précédemment

A détailler je pense pour qu'on ne se trompe pas.
Est-ce qu'on fait les traitements sur cette seule ligne de référence ou bien c'est une ligne en plus des autres ?

**Comment by mrouan** [comment]
dans le cas d'une ligne dessinée par l'utilisateur il ne faut pas afficher la ligne de référence "native"
