### ISSUE TITLE
TDC - mise à jour champ de sélection avec bouton tout sélectionner/déselectionner

### ISSUE THREAD

**Issue by mrouan** [jdev-org/madDog#42]
**Description du bug / Describe the bug**

Quand on sélectionne des dates puis que l'on clique sur tout selctionner ou tout déselectionner, le champ de selection affiche toujours les dates

**Reproduire le bug / To Reproduce**

Etapes à suivre pour reproduire votre problème du type : 

1. Aller sur la page https://gis.jdev.fr/mviewer/?config=apps/maddog.xml#
2. selectionner un site / trait de cote 
3. cliquer sur Tout désélectionner
4. selectionner quelques dates
5. cliquer sur Tout désélectionner
6. Voir que les dates reste affichées dans le champ de sélection

**Comportement attendu / Expected behavior**

le champ de selection doit être remis à zéro lors du clique sur Tout désélectionner
ou indiqué le nombre total de date (x selected) lors du clique sur Tout sélectionner

**Comment by Gaetanbrl** [comment]
Merci @mrouan je n'avais pas vu le text. On va corriger ca.
