### ISSUE TITLE
TDC - Supprimer la ligne de référence initiale quand on a une ligne de réf. dessinée

### ISSUE THREAD

**Issue by Agath21** [jdev-org/madDog#49]
> traitement -> si pas de ligne de REF dessinée, il faut afficher la ligne de REF par défaut

### Comportement actuel 
Lorsque l'on dessine une ligne de référence dans les paramètres avancées du suivi TDC, dans la partie résultat, la ligne de référence initiale et la ligne de référence dessinée sont représentées sur la carte

![image](https://user-images.githubusercontent.com/22764056/171627390-53a69e10-6609-4c2d-a5df-1f91c3c3604a.png)

### Comportement souhaité

- Quand pas de paramètres avancées = afficher la ligne de référence initiale au sein de la carte  dans la visualisation des résultats
- Quand ligne de référence dessinée = Afficher seulement la ligne de référence dessinée et supprimer la ligne initiale

**Comment by Agath21** [comment]
Note : On attends le retour de l'équipe LETG pour corriger ce point. L'affichage des deux lignes peut être un élément de comparaison

**Comment by Gaetanbrl** [comment]
@Agath21 bien noté.
Si on enlève la ligne de référence initiale, est-ce qu'on ne ferait pas mieux d'enlever les radiales aussi qui de toute façon seront recalculées ?

**Comment by mrouan** [comment]
Il faut en effet :
Quand ligne de référence dessinée = Afficher seulement la ligne de référence dessinée et supprimer la ligne initiale

**Comment by Gaetanbrl** [comment]
@mrouan c'est disponible et testable sur notre PF.
