### ISSUE TITLE
Lister les formats de données en entrée

### ISSUE THREAD

**Issue by pierrejego** [jdev-org/madDog#5]
Lister et essayer d'uniformiser les données d'entrée pour MADDOG et permettre ainsi de trouver un format commun, ou au moins limiter le nombre de format en entrée.

**Comment by mrouan** [comment]
[analyse format.docx](https://github.com/jdev-org/madDog/files/8152324/analyse.format.docx)
[format_pivot.xlsx](https://github.com/jdev-org/madDog/files/8152325/format_pivot.xlsx)
