### ISSUE TITLE
TDC - Affichage du bouton "Lancer le traitement" quand ligne de référence dessiné

### ISSUE THREAD

**Issue by Agath21** [jdev-org/madDog#50]
>Afficher le bouton "lancer le traitement" après dessin/annulation de la ligne de REF

**Reproduire le bug / To Reproduce**

Etapes à suivre pour reproduire votre problème du type : 

1. Dans le suivi TDC, on sélectionne des dates
2. Dans les paramètres avancées, on dessine une nouvelle ligne de référence 
3. On lance le traitement et on visualise les résultats
4. On clique sur l'onglet "Choix des dates" et on annule la ligne de référence dessiné "x Annuler"

**Problème :** Je ne peux pas relancer le traitement (bouton non apparent) sans modifier un autre paramètre ou cliquer sur "Réinitialiser"

![image](https://user-images.githubusercontent.com/22764056/171629364-1f93254a-cd56-4029-bba8-b1fcff46b4cd.png)

**Comportement attendu / Expected behavior**

Afficher le bouton "Lancer le traitement" quand on supprime seulement la ligne de référence dessinée préalablement
-> Evite de recommencer l'ensemble du processus de paramétrage si on veut visualiser les résultats avec la ligne initiale

**Comment by Agath21** [comment]
@Gaetanbrl c'est ok pour moi

**Comment by Gaetanbrl** [comment]
ok je clos
