### ISSUE TITLE
PRF - affichage carte et graphique

### ISSUE THREAD

**Issue by mrouan** [jdev-org/madDog#52]
## Description
Carte et IHM :

- [x] lors du choix d'un profil sur la carte il faut conserver son label au survol et l'afficher avec la même surbrillance que le profil.
- [x]  une fois selectionné il faut : 
    - soit conserver les autres profils sur la carte et affiché celui selectionné en surbrillance
    - soit n'afficher que celui qui a été séléctionné (en surbrillance ou non)
    - dans **site d'étude sélectionné** : conserver la nom du site

Graphique : 
- [x]  il faut afficher l'axe des abscisses sur une echelle temporelle, c'est à dire que l'écart entre 2 dates soit conservé (comme ici par exemple : https://managechart.univ-brest.fr/fr/chart/show/355/auto/auto)

**Comment by mrouan** [comment]
- paramètres avancés : il manque le + pour ouvrir la rubrique
- l'alerte "Attention" ajoute un point d'exclamation à chaque clique...
- bouton réinitialiser doit afficher le choix d'un profil

**Comment by Gaetanbrl** [comment]
> l'alerte "Attention" ajoute un point d'exclamation à chaque clique...

Vu, j'étais en train de faire des dev tu es tombé dessus au moment ou je faisais des modifications.

> bouton réinitialiser doit afficher le choix d'un profil

Je ne suis pas certain de comprendre ?

**Comment by mrouan** [comment]
Après avoir lancé un traitement, si on clique sur **Réinitialiser** il n'y a rien sur la carte.
Toutefois si on clique sur la carte les profils apparaissent, il serait préférable qu'ils apparaissent dès que l'on clique sur **réinitialiser**

**Comment by mrouan** [comment]
c'est ok pour ces points

> @mrouan est-ce que c'est possible de me valider sur notre plateforme que ces trois points sont corrigés ?
> 
>     * [X]  Invalides date sur le chart bilan sédimentaire PRF
> 
>     * [X ]  paramètres avancés : il manque le + pour ouvrir la rubrique
> 
>     * [X ]  l'alerte "Attention" ajoute un point d'exclamation à chaque clique...

**Comment by Gaetanbrl** [comment]
> lors du choix d'un profil sur la carte il faut conserver son label au survol et l'afficher avec la même surbrillance que le profil.
une fois selectionné il faut :
- soit conserver les autres profils sur la carte et affiché celui selectionné en surbrillance
- soit n'afficher que celui qui a été séléctionné (en surbrillance ou non)
- dans site d'étude sélectionné : conserver la nom du site


Des problèmes rencontrés avec la gestion de la souris :
- gestion du clic sur la commune ou site ==> Si pas de site visible avec le zoom, on retourne pas de site ==> On annule les traitements (pas de site => Pas de données TDC ou PRF)
- gestion du hover et select complexe en même temps que le clic sur un site

Pour gérer ce problème **j'ai désactivé de la recherche de site ou commune au clic si on est à un zoom < à la limite de visibilité de la couche des sites buffer**.

**Comment by Gaetanbrl** [comment]
> il faut afficher l'axe des abscisses sur une echelle temporelle, c'est à dire que l'écart entre 2 dates soit conservé

Affichage réalisé pour le bilan sédimentaire : 

![image](https://user-images.githubusercontent.com/16317988/172128614-2464156d-1f30-47e5-8ee3-15e56fbc9f72.png)
