### ISSUE TITLE
PRF - Multi select Ordre des dates 

### ISSUE THREAD

**Issue by Gaetanbrl** [jdev-org/madDog#53]
**Description du bug / Describe the bug**

Les dates ne sont pas dans le bon ordre

**Reproduire le bug / To Reproduce**

1. sélectionner un profil
2. Ouvrir la liste de choix pour une date
3. Voir l'ordre des dates

**Comment by mrouan** [comment]
sur le PRF1, il y a toujours le levé du 03/03/2022 qui est entre le 08/12/2004 et le 04/07/2004

**Comment by Gaetanbrl** [comment]
> sur le PRF1, il y a toujours le levé du 03/03/2022 qui est entre le 08/12/2004 et le 04/07/2004

En effet, pourquoi lui uniquement...

**Comment by Gaetanbrl** [comment]
@mrouan ca devrait être bon maintenant.

![image](https://user-images.githubusercontent.com/16317988/172400044-5d28389b-21da-478d-ba2b-9eb315b68f6e.png)

**Comment by mrouan** [comment]
pas sur firefox (même après avoir vidé le cache et testé sur une autre machine)
![Screenshot 2022-06-07 at 16-45-17 MadDog](https://user-images.githubusercontent.com/5336907/172410152-6295dd70-8877-4299-8c7a-f2d6cc749057.png)
Il y a également un pb de légende dans le selecteur

**Comment by Gaetanbrl** [comment]
les dates en JS + FireFox :see_no_evil:

**Comment by Gaetanbrl** [comment]
@mrouan je pense que tu peux tester à nouveau.
Je te laisse fermer l'issue si c'est bon (pour éviter de fermer / rouvrir).

**Comment by mrouan** [comment]
c'est bon pour l'ordre des dates mais j'ai encore un problème de couleur de légende
![Capture](https://user-images.githubusercontent.com/5336907/172551651-7bf74fc4-7322-47e6-8ad2-82e8cddd3108.PNG)

**Comment by Gaetanbrl** [comment]
@mrouan est-ce que ce problème est bien corrigé suite au dernier commit ?

**Comment by mrouan** [comment]
c'est corrigé, merci
