### ISSUE TITLE
IHM - Paramétrage et visualisation des résultats pour le service MNT

### ISSUE THREAD

**Issue by Agath21** [jdev-org/madDog#55]
## Description
En tant que Utilisateur
Je souhaite sélectionner deux MNT à des dates différentes au sein du site d'étude
Afin de visualiser la comparaison du terrain entre les 2 dates sur un nouveau MNT généré

## (Si) Règles spécifiques - Règles métiers
Deux dates doivent être sélectionnées
Cependant on ne limite pas la visualisation des MNT à deux dates avant le lancement du traitement
Le bouton "Réinitialiser" renvoie l'état initial c'est à dire une seule carte sans sélection de MNT

## Spécifications pour la visualisation des résultats 
-	Voir les trois topos en nuance de couleur (de froide sous la mer à chaud au-dessus)
         > Prendre en paramètre du SLD un niveau zéro
-	Résultat (couleur froide en négative chaude en positive)
- Synchronisation des deux cartes lors du déplacement de la souris

### À tester : 
Si possible rendre paramétrable le SLD de la TOPO, données stockées dans une table avec un ID_SITE afin d'adapter la valeur du zéro en fonction du site 

## (Si) Tests d'acceptabilité

- [ ]  Je peux sélectionner 2 dates via un système de liste
- [ ]  Je peux visualiser et comparer les MNT des dates sélectionnées sur la carte
- [ ]  Je peux modifier les paramètres initiaux du service WPS
- [ ]  Je peux visualiser la comparaison du terrain entre les 2 dates sur un nouveau MNT généré
- [ ]  Je peux exporter mes résultats en png

**Comment by Agath21** [comment]
# Solution(s) proposée(s)

## Maquettes
Scénario 1 : 
![3 13](https://user-images.githubusercontent.com/22764056/172351572-3dc19b9a-8458-40f9-a5ad-ce095dc77caa.png)

Scénario 2 : 
![3 23](https://user-images.githubusercontent.com/22764056/172351597-09dfdd47-feed-43f4-a55b-401527851572.png)
_Maquettes non contractuelles, les données visualisées sont inventées pour les besoins de compréhension des fonctionnalités_


## Parcours utilisateurs
Après avoir sélectionné le service "MNT" dans la liste, l'utilisateur doit suivre les étapes suivantes :

- Il paramètre le suivi en sélectionnant deux dates de MNT :
    - Je sélectionne Date 1 dans la 1 er liste > Le MNT associé s’affiche sur la carte
    - Je sélectionne Date 2 dans la 2 e liste > Le MNT associé s’affiche sur la carte 
- Je peux comparer les MNT des deux dates (fonctionnement à définir)
- Au besoin, je peux modifier les paramètres avancés du traitement
- Je lance le traitement via le bouton «Lancer le traitement »
- Je visualise le résultat dans la carte du bas (comparaison entre les 2)
- Je peux, au besoin, modifier à nouveau les paramètres et relancer le traitement


> NOTE (comportement de l'app) : 
> - Le déplacement est synchronisé pour l’ensemble des cartes
> - La sémiologie et classification est uniforme pour les 2 MNT sélectionnées et le MNT résultat (une seule légende)

## À définir

- [ ] Fonctionnement du suivi (Quel système pour visualiser l'ensemble des MNT en même temps ?) 
- [ ] Paramètres avancés + intitulés + textes descriptifs
- [ ] Représentation des MNT (sémiologie et classification)

**Comment by Agath21** [comment]
Maquettes et parcours utilisateurs MAJ dans l'issue suite au mail de @mrouan

**Comment by Gaetanbrl** [comment]
Premier rendu avec le SLD fourni par Mathias le 27/04/2022 : 
https://gis.jdev.fr/sviewer/?wmc=https%3A%2F%2Fgis.jdev.fr%2Fmapfishapp%2Fws%2Fwmc%2Fgeodoc3bf6de856992eb56fd752143d1a66470.wmc
