### ISSUE TITLE
Interface d'upload de données

### ISSUE THREAD

**Issue by pierrejego** [jdev-org/madDog#57]
## Description

**En tant que** fournisseur de données
**Je souhaite** uploader mes données
**Afin de** les rendre accessible dans l'application maddog

## (Si) Règles spécifiques - Règles métiers

L'utilisateur doit avoir accès à une page web protégé par mot de passe, lui permettant de sélection les champs : 
- Site
- Type de measure
- Choix du profil (unquiment en cas de mesure type PRF)
- Choix de la projection
- Choix d'un équipement de relevé
- Choix d'un opérateur

Il doit aussi pouvoir sélectionner une date pour ces relevés.

Le dernier champ doit être un champ permettant l'upload de fichier csv. Les fichiers d'entrées doivent respecter le format
id;x;y;z;identifiant;date

Le bouton de validation permet alors de créer l'arborescence de date manquante dans les données.
Il permettra aussi d'y déposer le fichier xxxx.meta créé à partir des champs sélectionné et le fichier xxxx.csv contenant les données.

L'intégration des données en base de donnée est réalisé par un autre script. 

## (Si) Tests d'acceptabilité

A définir

## Complément (graphique, capture, schéma, etc.)
![import_login](https://user-images.githubusercontent.com/22764056/172555857-bdc7af44-9078-47ed-a4b6-afef326bece6.png)
![import_form](https://user-images.githubusercontent.com/22764056/172555876-94ec2f74-5bd5-4e85-ad6f-ddb9d1bc0865.png)

**Comment by pierrejego** [comment]
Pour peupler les listes 

Via API Rest 
-> Choix du site -> maddogapi/site
-> Choix du type de mesure -> maddogapi/measure_type
-> Choix du numéro de profil -> non fonctionnel pour l'instant -> maddogapi/profil
-> Choix de l'opérateur -> maddogapi/operator
-> Choix de l'équipement -> maddogapi/equipment

Pour la date, il faut fournir un calendrier ( pas de données en base ) 

Pour la projection, il faut mettre les différentes valeurs dans un fichier de configuration ( pour l'instant valeur possible uniquement EPSG:2154)

Ces paramètres + le fichier csv seront envoyé en paramètre d'une service WPS qui déposera les données dans le bon répertoire

**Comment by Agath21** [comment]
### Tâches à réaliser

- [ ] Revoir l'intitulé des types de suivi / MNT,PRF,TDC = Modèle numérique de terrain, ...
- [ ] Afficher la sélection des profils seulement si le suivi PRF est sélectionné
- [ ] Mécanique pour uploader les données saisies

**Comment by Agath21** [comment]
> Revoir l'intitulé des types de suivi / MNT,PRF,TDC = Modèle numérique de terrain, Profil de plage, Trait de côte

@pierrejego , peut-on modifier les intitulés des suivis dans l'API ou faut-il le gérer dans la page ?

**Comment by Agath21** [comment]
> Gestion de l'authentification (.htaccess)

à tester sur le serveur, car non fonctionnel en local dans XAMPP

**Comment by Agath21** [comment]
### Restant à faire 

- [ ] Mécanique pour uploader les données saisies (WPS)

**Comment by Agath21** [comment]
![image](https://user-images.githubusercontent.com/22764056/173016633-ab01edcf-0715-4968-9047-397a4a4dbe4f.png)
