### ISSUE TITLE
IHM - réinitialisation paramètres

### ISSUE THREAD

**Issue by mrouan** [jdev-org/madDog#66]
**Description du bug / Describe the bug**

Lors du clique sur le bouton réinitialiser, les paramètres avancés doivent être réinitialiser

**Reproduire le bug / To Reproduce**

Etapes à suivre pour reproduire votre problème du type : 

1. choisir un type de données
2. modifier les paramètres avancés
3. lancer le traitement
4. afficher les resultats
5. cliquer sur réinitialiser
6. voir que les paramètres avancés ne sont pas réinitialisé
7. pour les profils, voir que le selecteur de profil n'est pas réinitialisé

**Comportement attendu / Expected behavior**

au clique sur réinitialiser les paramètres avancés doivent être remis à leur valeurs par défaut
le selecteur de profil doit être remis à "sélectionner un profil"

**Environnement / Desktop**

Merci de remplir ces informations si connues :
 - OS: [e.g. iOS] win 10
 - Navigateur / browser [e.g. chrome, safari] FF
 - Version [e.g. 22] 102

**Comment by pierrejego** [comment]
Vérifier pour l'ensemble des traitements

**Comment by Gaetanbrl** [comment]
> Vérifier pour l'ensemble des traitements

Cela veut dire que la réinitialisation ne fonctionne pas pour aucun traitement ?

**Comment by pierrejego** [comment]
Non c'est juste de bien vérifier que pour les trois types de données on réinitialise bien.

**Comment by Gaetanbrl** [comment]
Correctif visible [ICI](https://gis.jdev.fr/mviewer/?config=apps/maddog.xml#)

A valider.

**Comment by mrouan** [comment]
OK pour les paramètres TDC et MNT
KO pour le paramètre "Smallest Distance" pour les PRF
remarque : il faut traduire le libellé "Smallest Distance" en "Calcul sur le profil le plus court"

**Comment by Gaetanbrl** [comment]
> KO pour le paramètre "Smallest Distance" pour les PRF

Un oublie je pense.

> traduire le libellé "Smallest Distance" en "Calcul sur le profil le plus court"

ok pour la traduction.

**Comment by Gaetanbrl** [comment]
modifications poussées / à valider @mrouan

**Comment by mrouan** [comment]
OK
