### ISSUE TITLE
GENERAL - tooltip communes et sites n'apparaissent plus

### ISSUE THREAD

**Issue by mrouan** [jdev-org/madDog#67]
**Description du bug / Describe the bug**

Les tooltip au survol des communes et sites n'apparaissent plus

**Environnement / Desktop**

Merci de remplir ces informations si connues :
 - OS: [e.g. iOS] win 10
 - Navigateur / browser [e.g. chrome, safari] FF et Chrome
 - Version [e.g. 22] FF 102 Chrome 103

**Comment by pierrejego** [comment]
Non reproductible sur  https://portail.indigeo.fr/mviewer/?config=apps/maddog.xml#

**Comment by Gaetanbrl** [comment]
Idem, non reproductible sur Win 10, FF 103.0.2 et chrome Version 104.0.5112.81

**Comment by pierrejego** [comment]
Soucis d'url corrigées
