### ISSUE TITLE
MNT - le MNT le plus récent reste toujours affiché

### ISSUE THREAD

**Issue by mrouan** [jdev-org/madDog#75]
**Description du bug / Describe the bug**

le MNT le plus récent reste toujours affiché sur la carte même si on décoche toutes les dates.

**Comportement attendu / Expected behavior**

Lorsque aucune date n'est selectionnée, aucun MNT ne doit être affiché sur la carte

**Screenshots**
![Capture](https://user-images.githubusercontent.com/5336907/186871563-a6632544-f975-4cac-8379-1a2bb4188377.PNG)

**Environnement / Desktop**

Merci de remplir ces informations si connues :
 - OS: [e.g. iOS] win10
 - Navigateur / browser [e.g. chrome, safari] FF
 - Version [e.g. 22] 103.0.2

**Comment by pierrejego** [comment]
Problème de l'affichage par défaut.  en décochant tout la date par défaut reste visible alors que non coché

**Comment by pierrejego** [comment]
Après test, il s'avère que c'est le site par défaut de la couche WMS qui s'affiche. Comme pour la prévisualisation geoserver.
Donc par exemple si le tiff le plus récent c'est sur VOUGOT et qu'on est sur le site de BOUTRO pas de soucis on ne le voit pas pas. Par contre si on est sur VOUGOT la requête sans CQL_Filter renvoie le dernier MNT disponible par défaut (comme le preview geoserver)
L'appel sans date ne sert à rien, voir pour le supprimer
